export {default as Sample} from './Sample'
export {default as SimpleForm} from './SimpleForm'
export {default as LandingPage} from './LandingPage'
export {default as Home} from './Home'
export {default as ComingSoon} from './ComingSoon'