export {default as Testimonial} from './Testimonial'
export {default as Navbar} from './Navbar'
export {default as Rating} from './Rating'
export {default as Footer} from './Footer'
export {default as Routing} from './Routing'